add vector implementation.
ivanallen/dsa pull request #54
Opened 2019-05-15 04:28 UTC by zkangHUST

2019-05-15 05:51 UTC, ivanallen requested changes

2019-05-15 05:51 UTC, ivanallen commented on dsa/unsorted/testvector.cpp
> +    }
写正式一点吧，demo 放到 examples 下面。

2019-05-15 05:51 UTC, ivanallen commented on dsa/unsorted/vector.h
> +#ifndef MY_VECTOR_H
#pragma once

2019-05-15 05:51 UTC, ivanallen commented on dsa/unsorted/vector.h
> +template < class T>
dsa 库里统一 template <typename T> 
且命名空间为 namespace dsa

2019-05-15 05:51 UTC, ivanallen commented on dsa/unsorted/vector.h
> +void Vector<T>::push_back(const T& val)
如果 T 无法 copy 呢？

2019-05-15 05:51 UTC, ivanallen commented on dsa/unsorted/vector.h
> +void Vector<T>::push_back(const T& val)
可以再提供一个右值引用版本

2019-05-15 05:51 UTC, ivanallen commented on dsa/unsorted/testvector.cpp
> +    }
再加一个单元测试

2019-05-15 07:34 UTC, ivanallen requested changes
- unsorted 都是旧代码，都是不符合规范的。新代码就不要往这里加了。
- vector 的 example 应该放到 example 文件夹
- vector 应该需要加单元测试。

2019-05-15 07:34 UTC, ivanallen commented on dsa/unsorted/vector.h
> +    _buf = new T[1];
如果类型 T 没有默认构造函数呢？

2019-05-15 07:36 UTC, zkangHUST commented
> * unsorted 都是旧代码，都是不符合规范的。新代码就不要往这里加了。
> * vector 的 example 应该放到 example 文件夹
> * vector 应该需要加单元测试。
嗯 , gtest没用过，等我研究下

2019-05-16 09:58 UTC, ivanallen commented
This

2019-05-16 09:58 UTC, closed without merging